AWSTemplateFormatVersion: '2010-09-09'
Description: Testing Lambda controls
Transform: AWS::Serverless-2016-10-31
Resources:
  LayerXray:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
        - python3.9
      ContentUri: ../layer
      LayerName: boto3-1-20-6
  LayerXrayPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref LayerXray
      Principal: !Ref AWS::AccountId
Outputs:
  outLayerXray:
    Value: !Ref LayerXray