AWSTemplateFormatVersion: '2010-09-09'
Description: Testing Lambda controls
Transform: AWS::Serverless-2016-10-31
Parameters:
  pDescription:
    Type: String
Resources:
  LayerBoto3:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
        - python3.9
      ContentUri: ../layer
      LayerName: boto3
      Description: !Ref pDescription
  LayerBoto3Permission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref LayerBoto3
      Principal: !Ref AWS::AccountId
Outputs:
  outLayerBoto3:
    Value: !Ref LayerBoto3